config/routes.rb
ObjectBlog::Application.routes.draw do
  root :to => "blog#index"
  resource :posts
end

app/models/blog.rb
class Blog
  attr_writer :post_maker

  def initialize
    @posts = []
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinion"
  end
  
  def posts
    @posts.sort {|a, b| b.published_at <=> a.published_at}.take(10)
  end

  def new_post(*args)
    post_maker.call(*args).tap do |p|
      p.blog = self
    end
  end

  def add_post(post)
    @posts << post
  end

private
  def post_maker
    @post_maker ||= Post.public_method(:new)
  end
end

app/models/post.rb
# -*- encoding : utf-8 -*-
class Post
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :blog, :title, :body, :published_at, :image_url

  validates :title, :presence => true
  
  def initialize(attributes = {})
    attributes.each do |key, value|
      send("#{key}=", value)
    end 
  end

  def publish(clock = DateTime)
    return false unless self.valid?
    self.published_at = clock.now
    blog.add_post self
  end
  
  def persisted?
    false
  end
  
  def picture?
    image_url.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :init_blog

  helper :presenters

  private

  def init_blog
    @blog = THE_BLOG
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = @blog.new_post
  end

  def create
    @post = @blog.new_post(params[:post])
    if @post.publish
      redirect_to root_path, :notice => "Post added!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/presenters_helper.rb
module PresentersHelper
  def present(model, template)
    # Doing a string comparison because of Rails class-reloading weirdness
    case model.class.name
    when 'Post'
      if model.picture?
        PicturePostPresenter.new(model, template)
      else
        TextPostPresenter.new(model, template)
      end
    else
      model
    end
  end
end

app/views/blog/_post.html.erb
<% post = present(post, self) %>
<article>
  <header>
    <p><time pubdate="pubdate"><%= post.published_at %></time></p>
    <h3><%= post.title %></h3>
  </header>
  <%= post.render_body %>
</article>

app/views/blog/index.html.erb
<h1><%= @blog.title %></h1>
<p><%= @blog.subtitle %></p>
<%= render partial: "post", collection: @blog.posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ObjectBlog</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="error-messages">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <div class="sidebar two columns">
    <nav>
      <ul>
        <li><%= link_to "New post...", new_posts_path %></li>
      </ul>
    </nav>
  </div>

  <%= yield %>

</body>
</html>

app/views/posts/_picture_body.html.erb
<figure>
  <img src="<%= post.image_url %>"/>
  <figcaption><%= post.body %></figcaption>
<figure/>

app/views/posts/_text_body.html.erb
  <p><%= post.body %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>  
  <div id="errorExplanation">  
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>  
    <ul>  
    <% @post.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
  <% end %>

  <%= label :title, "Title:" %>
  <%= f.text_field :title %>

  <%= label :body, "Body:" %>
  <%= f.text_area :body %>

  <%= label :image_url, "Picture URL:" %>
  <%= f.text_field :image_url %>
  
  <%= f.submit %>
<% end %>